### ISSUE TITLE
links to plugins aren't live

### ISSUE THREAD

**Issue by pszczypka** [ibm-cloud-docs/cli#1]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

links to COS plugins etc. aren't live

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/cli?topic=cli-getting-started

4. Do you have a suggestion about how to resolve the issue?
Fix the links?

**Comment by michaelbowler** [comment]
@pszczypka links in https://cloud.ibm.com/docs/cli?topic=cli-getting-started are now resolved, pls close.
