### ISSUE TITLE
Using IBM Cloud Developer Tools from a Docker Container - curl is missing in the dockerfile

### ISSUE THREAD

**Issue by thomassuedbroecker** [ibm-cloud-docs/cli#102]
curl is missing in the docker image `ibmcom/ibm-cloud-developer-tools-amd64`  and can not be installed manual in that image.

No additional installation possible:
```
/ # sudo apt-get update
/bin/sh: sudo: not found
```

Missing CURL
```
PS C:\Users\thomassuedbroecker\documents\cloud-native-starter> docker run -ti ibmcom/ibm-cloud-developer-tools-amd64
/ # ls
bin    dev    etc    home   lib    media  mnt    opt    proc   root   run    sbin   srv    sys    tmp    usr    var
/ # curl
/bin/sh: curl: not found
/ #
```

1. What are the details of the issue you're experiencing?
Information is wrong in documentation: Using IBM Cloud Developer Tools from a Docker Container 

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/cli?topic=cloud-cli-using-idt-from-docker

3. Do you have a suggestion about how to resolve the issue?
Install curl in the docker image

**Comment by jpkessle** [comment]
@clays Hey Steve, can you please take a look at this issue? Thanks!

**Comment by jpkessle** [comment]
@clays Can you please provide feedback on this issue? Thanks!

**Comment by bhpratt** [comment]
To install curl in your container:

`apk update`
`apk upgrade`
`apk add curl`

**Comment by bhpratt** [comment]
That being said, the image should be updated to add curl as documented.

**Comment by jpkessle** [comment]
@thomassuedbroecker Thanks for bringing this to our attention. I will update the documentation to no longer include `curl` support as part of the image. Should curl support be added back at a future date, we will update the image and documentation accordingly. 

Sorry for any confusion.
