### ISSUE TITLE
Unable to install the latest version of the IBM Cloud CLI on Mac (10.14.2)

### ISSUE THREAD

**Issue by sayom88** [ibm-cloud-docs/cli#103]
1. What are the details of the issue you're experiencing? Unable to install the latest version of the IBM Cloud CLI on Mac (10.14.2). Whenever I am trying to run the command **curl -sL https://ibm.biz/idt-installer | bash** from the terminal, it is throwing an error like below:
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">'

Any help will be highly appreciated here please. Thanks.

**Comment by jpkessle** [comment]
@sayom88 Are you still experiencing a problem with the CLI installation?
