### ISSUE TITLE
Error installing ibm cloud cli using the powershell script

### ISSUE THREAD

**Issue by mrememisaac** [ibm-cloud-docs/cli#104]
1. What are the details of the issue you're experiencing?
 iex(New-Object Net.WebClient).DownloadString('https://clis.cloud.ibm.com/install/powershell')
Current platform is Win64. Downloading corresponding IBM Cloud CLI...
Exception calling "GetResponse" with "0" argument(s): "The operation has timed out"
At line:22 char:1
+ $resp = $req.GetResponse()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Start-BitsTransfer : Cannot validate argument on parameter 'Source'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:23 char:28
+ Start-BitsTransfer -Source "$($resp.ResponseUri.AbsoluteUri)" -Destin ...
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Start-BitsTransfer], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.BackgroundIntelligentTransfer.Management.NewBitsTransferCommand

Download complete. Executing installer...
& : The term 'C:\Users\E798\AppData\Local\Temp\IBM_Cloud_CLI.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if
a path was included, verify that the path is correct and try again.
At line:27 char:3
+ & $DownloadedInstaller /s /v"REBOOT=ReallySupress /qn"
+   ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\E798\A...M_Cloud_CLI.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/cli?topic=cloud-cli-install-ibmcloud-cli

3. Do you have a suggestion about how to resolve the issue?
The poweshell script supposedly calls a getResponse() function without an argument, the argument should be supplied

**Comment by mrememisaac** [comment]
This issue also occurs when following instructions on this page https://cloud.ibm.com/docs/cli?topic=cloud-cli-getting-started

Installing 'ibmcloud' CLI for Windows...
[install_ibmcloud] Downloading and installing 'ibmcloud' CLI from: https://clis.ng.bluemix.net/install/powershell
Current platform is Win64. Downloading corresponding IBM Cloud CLI...
Exception calling "GetResponse" with "0" argument(s): "The operation has timed out"
At line:22 char:1
+ $resp = $req.GetResponse()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Start-BitsTransfer : Cannot validate argument on parameter 'Source'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:23 char:28
+ Start-BitsTransfer -Source "$($resp.ResponseUri.AbsoluteUri)" -Destin ...
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Start-BitsTransfer], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.BackgroundIntelligentTransfer.Management.NewBitsTransferCommand

**Comment by jpkessle** [comment]
@mrememisaac Are you still experiencing the installation issue? Which Windows platform are you running? You state "Win64". Is this Windows 7 or Windows 10?

**Comment by jpkessle** [comment]
The timed out message indicates that you are experiencing an issue with connectivity on your end. Can you access another entirely separate network and try the install again?

"Operation timed out" means that your client system is unable to reach the URL.
