### ISSUE TITLE
IBM CLI hyperlink to 'IBM Cloud Object Storage command reference' directs people to a 404 page

### ISSUE THREAD

**Issue by brnnnfx** [ibm-cloud-docs/cli#11]
1. What are the details of the issue you're experiencing?

A hyperlink in the IBM CLI docs directs readers to a 404 error page

3. Is this issue in reference to a specific page? If so, please provide a link.

- Navigate to https://cloud.ibm.com/docs/cli?topic=cli-install-devtools-manually#install-cos-cli-plugin
- Select the link for [IBM Cloud Object Storage command reference](https://cloud.ibm.com/cloud-object-storage-cli-plugin?topic=cloud-object-storage-cli-plugin-ic-cos-cli).
- You will be directed to https://cloud.ibm.com/cloud-object-storage-cli-plugin?topic=cloud-object-storage-cli-plugin-ic-cos-cli , which is a 404 page

![404Page](https://user-images.githubusercontent.com/12024098/184456290-f7bb444c-38e1-40ec-9700-6d1eaf525670.jpg)

**Comment by christoc-ibm** [comment]
Thank you for pointing out this broken link. I've fixed the .md file and started a doc build. As soon as that's finished, the link will be fixed.

Thanks again!
