### ISSUE TITLE
Install of ibmcloud CLI fails on MacOS Catalina

### ISSUE THREAD

**Issue by petervansickel** [ibm-cloud-docs/cli#110]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

From this page: https://cloud.ibm.com/docs/cli?topic=cloud-cli-getting-started

Here is the command sequence and error:
$ curl --insecure -sL https://ibm.biz/idt-installer | bash
[main] --==[ IBM Cloud Developer Tools for Linux/MacOS - Installer, v1.2.3 ]==--
[install] Starting Update...
[install] Note: You may be prompted for your 'sudo' password during install.
[install_darwin_deps] Checking for external dependency: brew
[install_darwin_deps] Installing/updating external dependency: git
[install_darwin_deps] Installing/updating external dependency: docker
[install_darwin_deps] Installing/updating external dependency: kubectl
[install_darwin_deps] Installing/updating external dependency: helm
[install_ibmcloud] Installing IBM Cloud 'ibmcloud' CLI for platform 'Darwin'...
[install_ibmcloud] Downloading and installing IBM Cloud 'ibmcloud' CLI from: https://clis.ng.bluemix.net/install/osx
curl: (60) SSL: no alternative certificate subject name matches target host name 'clis.ng.bluemix.net'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
[install_ibmcloud] IBM Cloud 'ibmcloud' CLI install finished.
[install_ibmcloud] Running 'ibmcloud --version'...
main: line 312: ibmcloud: command not found
[install_plugins] Installing/updating IBM Cloud CLI plugins...
[install_plugins] Checking status of plugin: cloud-functions
main: line 329: ibmcloud: command not found
[install_plugins] Installing plugin 'cloud-functions'
main: line 332: ibmcloud: command not found
[install_plugins] Checking status of plugin: cloud-object-storage
main: line 329: ibmcloud: command not found
[install_plugins] Installing plugin 'cloud-object-storage'
main: line 332: ibmcloud: command not found
[install_plugins] Checking status of plugin: container-registry
main: line 329: ibmcloud: command not found
[install_plugins] Installing plugin 'container-registry'
main: line 332: ibmcloud: command not found
[install_plugins] Checking status of plugin: container-service
main: line 329: ibmcloud: command not found
[install_plugins] Installing plugin 'container-service'
main: line 332: ibmcloud: command not found
[install_plugins] Checking status of plugin: dev
main: line 329: ibmcloud: command not found
[install_plugins] Installing plugin 'dev'
main: line 332: ibmcloud: command not found
[install_plugins] Running 'ibmcloud plugin list'...
main: line 339: ibmcloud: command not found
[install_plugins] Finished installing/updating plugins
[install] Install finished.
[main] --==[ Total time: 1 seconds ]==--

Here is what I did to work around the issue:
$ curl -k -sL https://clis.ng.bluemix.net/install/osx | bash
Current platform is macOS. Downloading corresponding IBM Cloud CLI...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   111    0   111    0     0    462      0 --:--:-- --:--:-- --:--:--   460
100 18.1M  100 18.1M    0     0  5882k      0  0:00:03  0:00:03 --:--:-- 8627k
Download complete. Executing installer...
Password:
installer: Package name is IBM Cloud Command Line Interface
installer: Installing at base path /
installer: The install was successful.
Install complete.
pvs10:hre pvs@us.ibm.com$ which ibmcloud
/usr/local/bin/ibmcloud
pvs10:hre pvs@us.ibm.com$ ic --version
ibmcloud version 0.20.0+5d69177-2019-10-31T09:49:54+00:00

Note the work-around I used the -k option for curl command to avoid the certificate check.  I also had to use the URL for just the ibmcloud install.  When I used the -k option on the top level, idt-installer URL that didn't get passed through to the curl of the ibmcloud CLI itself.

Could be this is something that has only come up recently with Catalina and not prior versions of MacOS.

**Comment by cjcarpen** [comment]
Thanks for reporting, @petervansickel ! We're looking into this issue.

**Comment by steveclay** [comment]
This was a temporary problem in the networking. The installer is now working normally, again. Sorry for the inconvenience.

**Comment by petervansickel** [comment]
Hey, thanks for quick response.
