### ISSUE TITLE
sshkey-add: Incorrect Usage: This command requires one argument.

### ISSUE THREAD

**Issue by ebubekirtabak** [ibm-cloud-docs/cli#113]
Hi, 

I got it from this topic.
[https://cloud.ibm.com/docs/cli?topic=cloud-cli-sl-manage-security-keys](url)
I get this error when I trying to add ssh key. I couldn't found the message on the knowledge center.

[https://www.ibm.com/support/knowledgecenter/search/This%20command%20requires%20one%20argument?scope=STSLR9_8.2.1](url)

**Command:**

```bash 
ibmcloud sl security sshkey-add -f ~/.ssh/id_rsa.pub --note mykey
```

**Result:**

```bash
Incorrect Usage: This command requires one argument.
```

![image](https://user-images.githubusercontent.com/36111436/71803279-66a8d600-3071-11ea-83a8-f5b6aabd7277.png)

** Os Details: **

```bash
ProductName:	Mac OS X
ProductVersion:	10.15.1
BuildVersion:	19B88
```

Thanks

**Comment by cjcarpen** [comment]
Hi @ebubekirtabak , thanks for bringing this issue to our attention! It looks like the example is missing the label for the added key. Try running the command in the following format (replacing the `MyLabel`, `-f` and `--note` values with the ones for your system):

```
ibmcloud sl security sshkey-add MyLabel -f ~/.ssh/id_rsa.pub --note mykey
```

We'll update the documentation to include the label in the example.

**Comment by cjcarpen** [comment]
Updated documentation is here: https://cloud.ibm.com/docs/cli?topic=cloud-cli-sl-manage-security-keys

**Comment by ebubekirtabak** [comment]
Thanks so munch
