### ISSUE TITLE
Documentation error 

### ISSUE THREAD

**Issue by kdixonIBM** [ibm-cloud-docs/cli#114]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

re: documentation page at https://cloud.ibm.com/docs/cli?topic=cloud-cli-sl-manage-classic-orders
"ibmcloud sl order package-locations" is listed twice. Based on the description, I believe the first instance should be "ibmcloud sl order package-list" instead.

**Comment by christoc-ibm** [comment]
Thank you for pointing out the error.

I checked the CLI itself, and it looks like we have two errors:

The command should be `ibmcloud sl order category-list`, so I changed that in the source.

The doc is missing the command `ibmcloud sl order package-list`, so I'm adding that command and will have dev complete the details.

**Comment by christoc-ibm** [comment]
https://github.ibm.com/cloud-docs/cli/pull/245

**Comment by christoc-ibm** [comment]
The doc is updated here:
https://cloud.ibm.com/docs/cli?topic=cloud-cli-sl-manage-classic-orders

Thank you again for pointing out the error.
