### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by guykhazma** [ibm-cloud-docs/cli#115]
I am trying to install the IBM Cloud CLI as explained here:
https://cloud.ibm.com/docs/cli?topic=cloud-cli-getting-started#idt-prereq

It seems that the following link is broken:
```
https://ibm.biz/idt-installer
```
The following command doesn't succeed:
```
curl -sL https://ibm.biz/idt-installer | bash
```

**Comment by steveclay** [comment]
@guykhazma sorry for this difficulty. Please see this page that has the work-around for this problem: https://cloud.ibm.com/docs/cli?topic=cloud-cli-troubleshoot#the-ibm-biz-short-url-is-unreachable-for-cli-dev-plug-in-installation

**Comment by guykhazma** [comment]
@steveclay thanks!
