### ISSUE TITLE
ibmcloud catalog search not a command

### ISSUE THREAD

**Issue by chanster** [ibm-cloud-docs/cli#116]
1. What are the details of the issue you're experiencing?
[Document](https://cloud.ibm.com/docs/cli/reference/ibmcloud?topic=cloud-cli-ibmcloud_catalog#ibmcloud_catalog_search) states to search catalog, run the `ibmcloud search <QUERY>`

But when running the command, it outputs error:
```
ibmcloud catalog search db2
FAILED
'search' is not a registered command. See 'ibmcloud catalog help'.
```

```
ibmcloud --version
ibmcloud version 1.0.0+908f90a-2020-03-30T06:37:22+00:00
```

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/cli/reference/ibmcloud?topic=cloud-cli-ibmcloud_catalog#ibmcloud_catalog_search

3. Do you have a suggestion about how to resolve the issue?
Update documentation to provide correct option for searching catalog

**Comment by cjcarpen** [comment]
Hi @chanster ! Thanks for your feedback. The documentation has been updated to remove this command from the core CLI. To run the `ibmcloud catalog search` command, please install the catalog management plug-in by running the following command:
```
ibmcloud plugin install catalogs-management
```

For details about this and other commands in the catalog management plug-in, check out: https://cloud.ibm.com/docs/cli?topic=cloud-cli-manage-catalogs-plugin
