### ISSUE TITLE
Travelkit

### ISSUE THREAD

**Issue by balaguru854** [ibm-cloud-docs/cli#117]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by cjcarpen** [comment]
Hi @balaguru854, I'm closing this issue because I don't see a description for suggested updates in the issue, but please feel free to reopen if you have any questions about the IBM Cloud CLI docs. Thanks!
