### ISSUE TITLE
ibmcloud plugin install dev 

### ISSUE THREAD

**Issue by ganand40** [ibm-cloud-docs/cli#120]
I am using Windows 10 Pro and while installing ibmcloud dev plugin through command line (command which I am using ibmcloud plugin install dev) is returning error as below:

Installing binary...
FAILED
Plug-in 'dev' is already in use in IBM Cloud CLI.

Anyone please help me out.

**Comment by cjcarpen** [comment]
@ganand40 With the release of Version 1.0.0 of the IBM Cloud CLI, the previously separately installed `dev` plug-in was bundled into the core CLI. See details here: https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases/tag/v1.0.0

Try running `ibmcloud dev help` to see if you already have it installed. If you see command output, you're good to go!

If you get a "Failed - unrecognized command" error, we recommend updating to the latest version of the IBM Cloud CLI, which you can do by running `ibmcloud update`.

Hope this helps!

**Comment by christx83** [comment]
No response yet, so closing.
