### ISSUE TITLE
ibmcom/ibm-cloud-developer-tools-amd64 DockerHub Image Outdated

### ISSUE THREAD

**Issue by lindluni** [ibm-cloud-docs/cli#128]
Are there plans to update the `ibmcom/ibm-cloud-developer-tools-amd64` image on DockerHub? The version of the CLI embedded in the image is 4 months old and missing many features/flags mentioned in the doc. Since this container image is mentioned as part of the official doc I would expect it to be kept up to date.

**Comment by christoc-ibm** [comment]
Created an internal issue for this:
https://github.ibm.com/ibmcloud-cli/bluemix-cli/issues/3916
