### ISSUE TITLE
Password Not Showing on Cloudant Request

### ISSUE THREAD

**Issue by SaginiChan** [ibm-cloud-docs/cli#129]
**Below is the command used to getting the service keys as stated in the tutorials:**
C:\Users\boazs\dWTVAdvancedApp>bx cf service-keys Cloudant-gp
Invoking 'cf service-keys Cloudant-gp'...

Getting keys for service instance Cloudant-gp as boazsagini62@gmail.com...

name
newkey

C:\Users\boazs\dWTVAdvancedApp>bx cf service-key Cloudant-gp newkey
Invoking 'cf service-key Cloudant-gp newkey'...

**However,,no field/Parameter for the Password is present**
_Getting key newkey for service instance Cloudant-gp as boazsagini62@gmail.com..._

{
 "apikey": "KvQ_LKEBxIIRK6pOvK7TStfDNNXysDwEoifoOGWXF1mk",
 "host": "e6012d92-7bab-43a4-9486-bd912443b9a4-bluemix.cloudantnosqldb.appdomain.cloud",
 "iam_apikey_description": "Auto-generated for key 0546d476-e77a-4256-ae2f-5f30d0281559",
 "iam_apikey_name": "Credentials-qv",
 "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Writer",
 "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/7e1d627e6f614724b237ca1189c5fe6b::serviceid:ServiceId-cf13245d-0be1-410c-b799-4cbaeaf36482",
 "url": "https://e6012d92-7bab-43a4-9486-bd912443b9a4-bluemix.cloudantnosqldb.appdomain.cloud",
 "username": "e6012d92-7bab-43a4-9486-bd912443b9a4-bluemix"
}

Thus, this error is reflected on beginning the **npm start** command
C:\Users\boazs\dWTVAdvancedApp>npm start

> WebinarRegistration@0.0.1 start C:\Users\boazs\dWTVAdvancedApp
> node app.js

C:\Users\boazs\dWTVAdvancedApp\node_modules\cloudant\lib\reconfigure.js:124
  var result = {password: config.password, username: config.key || config.username || config.account};
                                 ^

**Comment by steveclay** [comment]
Have you seen this article for using Cloudant with Cloud Foundry:  https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-creating-an-ibm-cloudant-instance-on-ibm-cloud-by-using-the-ibm-cloud-cli ? The instructions seem different than the tutorial you mentioned above.

You may also try the sample code here as an example: https://github.com/IBM-Cloud/get-started-node
