### ISSUE TITLE
The CLI could ask me directly to install plugins for me

### ISSUE THREAD

**Issue by rodet** [ibm-cloud-docs/cli#133]
1. What are the details of the issue you're experiencing?

Starting with a new machine, I had to install the `ibmcloud` CLI from scratch. I immediately started to use cloud foundry, which of course didn't work because the plugin was not installed yet:
![image](https://user-images.githubusercontent.com/343696/98384712-66d97f80-204e-11eb-9834-57d296d98bc8.png)

As the command told me what I should do, I wondered why the tool wouldn't simply propose to install the plugin for me if I'm ok with it.

2. Is this issue in reference to a specific page? If so, please provide a link.
I don't think this belong on the documentation, it is more a product aspect. This might make [the documentation](https://cloud.ibm.com/docs/cli?topic=cli-install-devtools-manually) simpler, as a consequence though, as users wouldn't have to be guided manually through the plugin install, they would just do an initial call to the capability they want... K8s, Cloud Foundry, etc. "To get started with Cloud Foundry, just type `ibmcloud cf` and you'll be ready in a few minutes."

3. Do you have a suggestion about how to resolve the issue?
The command should go along the way of
```
The Cloud Foundry plugin isn't installed yet on this system. Do you want to install it?
[Y/n]
```
That would make the experience of adding more cloud capability much more seamless. Also, removing the red FAILED would be nice.

**Comment by christoc-ibm** [comment]
I created an internal dev issue for this, so I'm closing this external issue that was created in the doc repo. Thank you!

https://github.ibm.com/ibmcloud-cli/bluemix-cli/issues/3919
