### ISSUE TITLE
HomeBrew documentation missing

### ISSUE THREAD

**Issue by chris-zenfolio** [ibm-cloud-docs/cli#134]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
I'm looking to install the IBM CLI tools using homebrew and there are no instructions

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/cli?topic=cli-getting-started

3. Do you have a suggestion about how to resolve the issue?
On the Getting Started page, it refers to Homebrew.  Please provide a link to instruction on how to install the IBM CLI using Homebrew.  https://formulae.brew.sh/cask/ibm-cloud-cli  If there is a separate formula for plugins, please provide it!

**Comment by christoc-ibm** [comment]
Created an internal issue for this:
https://github.ibm.com/Bluemix/bluemix-cli-docs/issues/54
