### ISSUE TITLE
IBM Cloud CLI installation is long as it is doing lot others and not everyone needs all of it.

### ISSUE THREAD

**Issue by rgentyala** [ibm-cloud-docs/cli#139]
Below link and topic extensively installs other software and with lot of errors. It helps if there is a single command that can just install IBM Cloud CLI just like for Linux. Takes a long time to run as well on Windows. All in all just accessing a windows server with these different methods making everything so complex.

https://cloud.ibm.com/docs/cli?topic=cli-getting-started

or Windows™ 10 Pro, run the following command in PowerShell as an administrator:

[Net.ServicePointManager]::SecurityProtocol = "Tls12, Tls11, Tls, Ssl3"; iex(New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/IBM-Cloud/ibm-cloud-developer-tools/master/windows-installer/idt-win-installer.ps1')

**Comment by tushortz** [comment]
@rgentyala  i think #141 will help you

**Comment by christoc-ibm** [comment]
The installation instructions and process are updated:
https://cloud.ibm.com/docs/cli?topic=cli-getting-started
