### ISSUE TITLE
Search for "cli private endpoint" in docs returns no hit

### ISSUE THREAD

**Issue by l2fprod** [ibm-cloud-docs/cli#140]
I was searching on how to use private endpoints with the CLI.

Searching for https://cloud.ibm.com/docs/search?q=cli+private+endpoint does not return what I was expecting.

I would expect the search to point me to https://cloud.ibm.com/docs/cli?topic=cli-service-connection

**Comment by christoc-ibm** [comment]
Try searching for "private endpoint" - and you should see a few hits now.

https://cloud.ibm.com/docs/search?q=private+endpoint&tags=cli
