### ISSUE TITLE
Add a large warning to the CLI install instructions

### ISSUE THREAD

**Issue by ssorj** [ibm-cloud-docs/cli#142]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

The docs duped me into violating the integrity of my machine.

2. Is this issue in reference to a specific page? If so, please provide a link.

https://cloud.ibm.com/docs/cli?topic=cli-install-ibmcloud-cli - The curl snippets.

3. Do you have a suggestion about how to resolve the issue?

That needs a big warning!  (Hell, don't *do  that in the first instance*.  It's crazy pants.)  The snippet offered there downloads a script from the internet and runs it with root privileges if the local sudo permits it.  That's very bad.  Now I have a trust issue.  I have to inspect everything IBM's docs are telling me to do because it might be up to scary hijinx.

**Comment by christoc-ibm** [comment]
Looking into this...

**Comment by christoc-ibm** [comment]
@ssorj - Thank you for pointing this out.

We've added a statement to the doc:
https://cloud.ibm.com/docs/cli?topic=cli-install-ibmcloud-cli#shell_install
