### ISSUE TITLE
Remove curl from list of installed features in the CLI Docker image

### ISSUE THREAD

**Issue by steveclay** [ibm-cloud-docs/cli#145]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
The doc says `curl` is included in the image, but it is not.

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/cli?topic=cli-using-idt-from-docker

3. Do you have a suggestion about how to resolve the issue?
Remove `curl` from the list of installed items.

**Comment by christoc-ibm** [comment]
This doc topic no longer exists, so I'm closing this issue.
