### ISSUE TITLE
Please add Key Protect CLI Plugin to list of offerings with plugins

### ISSUE THREAD

**Issue by cloudpitchford** [ibm-cloud-docs/cli#149]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

   This issue: https://github.ibm.com/Bluemix/Documentation-content/issues/17264 has been filed stating that the Key Protect CLI Plugin with the public repo here: https://github.com/ibm-cloud-docs/key-protect-cli-plugin needs to be referenced by the CLI team maintaining this repo along with the list of other offering's plugins.

2. Is this issue in reference to a specific page? If so, please provide a link.

   List of offering's plugins in TOC.

3. Do you have a suggestion about how to resolve the issue?

   Please add the repo: https://github.com/ibm-cloud-docs/key-protect-cli-plugin to the TOC. Thanks!

**Comment by cloudpitchford** [comment]
@christoc-ibm can you check this, please? Thanks!

**Comment by christoc-ibm** [comment]
@cloudpitchford - Yes, I'll check into this. Thank you for tagging me!

**Comment by christoc-ibm** [comment]
This is now published in the main CLI ToC:
https://cloud.ibm.com/docs/cli?topic=key-protect-cli-plugin-key-protect-cli-reference
