### ISSUE TITLE
Feature Request Autocomplete Fish Shell

### ISSUE THREAD

**Issue by PKehnel** [ibm-cloud-docs/cli#153]
Currently as stated in the [docs](https://cloud.ibm.com/docs/cli?topic=cli-shell-autocomplete) autocomplete is only available for `Bash` and `Zsh`.

Would be cool if this feature would be implemented for the [Fish Shell](https://fishshell.com/) as well.

**Comment by christoc-ibm** [comment]
Created internal issue https://github.ibm.com/ibmcloud-cli/bluemix-cli/issues/3917 for consideration. Thank you.
