### ISSUE TITLE
Update the ibmcloud resource search to document --is-reclaimed option

### ISSUE THREAD

**Issue by mkrudele** [ibm-cloud-docs/cli#2]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?  

Starting from the version 2.14.0, the ibmcloudcli resource search command will have an additional option `--is-reclaimed` (see section https://cloud.ibm.com/docs/cli?topic=cli-ibmcloud_commands_resource#ibmcloud_resource_search).  
The new usage section shows:  
```
ibmcloud resource search LUCENE_QUERY [-o, --offset OFFSET] [-l, --limit LIMIT] [-s, --sort-by (name, family, region, type, crn)] [-p, --provider PROVIDER] [-ir, --is-reclaimed (false, true, any)] [--output FORMAT]
```

The `--is-reclaimed` option gives to the end user the possibility to search for account resources that have been reclaimed.  
By default the search returns only active resources, however the user can:  
- set `is-reclaimed` to `any` to search for resources regardless of whether they have been reclaimed or not;
- set `is-reclaimed` to `true` to apply the search criteria only to reclaimed resources;  
- explicitly set the `is-reclaimed` to `false` to search only for active resources. That is the default behaviour, so the flag can be omitted.  

2. Is this issue in reference to a specific page? If so, please provide a link.  

https://cloud.ibm.com/docs/cli?topic=cli-ibmcloud_commands_resource#ibmcloud_resource_search  

3. Do you have a suggestion about how to resolve the issue?

See bullet 1. above.

**Comment by michaelbowler** [comment]
@mkrudele, I'm not sure I understand the change you want to see.

You say "see bullet 1", but that bullet is already represented in the text as: "...however you can set is-reclaimed to any to search for resources whether they have been reclaimed or not."

Could you clarify pls?

**Comment by mkrudele** [comment]
Well, I think it has been fixed. The page https://cloud.ibm.com/docs/cli?topic=cli-ibmcloud_commands_resource#ibmcloud_resource_search looks good.

**Comment by michaelbowler** [comment]
@mkrudele - great, pls close this issue at your convenience.
