### ISSUE TITLE
set default resource group in CLI

### ISSUE THREAD

**Issue by TiloGit** [ibm-cloud-docs/cli#2]
https://cloud.ibm.com/docs/cli?topic=cli-ibmcloud_commands_resource#ibmcloud_resource_groups

How to specify a new default resource group to use in session or permanent for the account?

**Comment by TiloGit** [comment]
found it. at login. wasn't obvious as I used cloud shell. 

`ibmcloud login -r us-south -g my-rg  --sso`

**Comment by TiloGit** [comment]
tried this as well but no luck. 

`ibmcloud target -g my-rg`

**Comment by Aerex** [comment]
>  A default resource group is created when an account is created. If you have a Lite account or 30-day trial, you cannot create extra resource groups, but you can rename your default resource group. ([doc](https://cloud.ibm.com/apidocs/resource-controller/resource-manager#create-resource-group))

@TiloGit According to the docs, you might not be able to set the default resource group but you can rename it. 

`ibmcloud resource group-update Default -n Default-New`
