### ISSUE TITLE
Hyperlinks are wrong

### ISSUE THREAD

**Issue by kmadhushree** [ibm-cloud-docs/cli#3]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
https://cloud.ibm.com/docs/cli?topic=cli-getting-started
In the above link there are hyperlinks for the installations of below plugins:
[IBM Cloud Functions plug-in](https://cloud.ibm.com/docs/cli?topic=cloud-functions-cli-plugin-functions-cli)
[IBM Cloud Object Storage plug-in](https://cloud.ibm.com/docs/cli?topic=cloud-object-storage-cli-plugin-ic-cos-cli)
[IBM Cloud Container Registry plug-in](https://cloud.ibm.com/docs/cli?topic=container-registry-cli-plugin-containerregcli)
[IBM Cloud Kubernetes Service plug-in](https://cloud.ibm.com/docs/cli?topic=containers-kubernetes-service-cli)

However these links lead to pages that don't exist. (Refer screenshot attached)

3. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/cli?topic=cli-getting-started

5. Do you have a suggestion about how to resolve the issue?
You can link it to the below links for respective services:
https://cloud.ibm.com/docs/cli?topic=cli-install-devtools-manually#idt-install-functions
https://cloud.ibm.com/docs/cli?topic=cli-install-devtools-manually#install-cos-cli-plugin
https://cloud.ibm.com/docs/cli?topic=cli-install-devtools-manually#idt-install-container-registry-cli-plugin
https://cloud.ibm.com/docs/cli?topic=cli-install-devtools-manually#idt-install-kubernetes-cli-plugin

<img width="430" alt="image" src="https://user-images.githubusercontent.com/104574223/217145041-e7406896-8f34-49b2-baf4-c1503bcdbc7f.png">

**Comment by michaelbowler** [comment]
@mkulamarva  Updates made in the doc: https://cloud.ibm.com/docs/cli?topic=cli-getting-started

Pls close.
