### ISSUE TITLE
Doc issue: Broken link at page "Installing the tools and plug-ins manually"

### ISSUE THREAD

**Issue by sofia-herrera** [ibm-cloud-docs/cli#4]
1. What are the details of the issue you're experiencing?
     Broken link on below page:

**page**: https://cloud.ibm.com/docs/cli?topic=cli-install-devtools-manually
**paragraph** : "Installing IBM Cloud Container Registry CLI plug-in"
**Broken link**: "IBM Cloud® Container Registry command reference."

2. Is this issue in reference to a specific page? If so, please provide a link.
Yes , the specific page "https://cloud.ibm.com/docs/cli?topic=cli-install-devtools-manually" contains an hyperlink broken.
That link is located at under  "Installing IBM Cloud Container Registry CLI plug-in" paragraph.
The broken hyperlink caption is : "IBM Cloud® Container Registry command reference"

![image](https://user-images.githubusercontent.com/130024931/233754486-1452d33d-1d4b-4d80-952d-54a1476e478e.png)

3. Do you have a suggestion about how to resolve the issue?
IT should open the correct  page.

**Comment by christoc-ibm** [comment]
@michaelbowler - For your action. Thank you!

**Comment by michaelbowler** [comment]
@sofia-herrera. Link is now fixed, pls see https://cloud.ibm.com/docs/cli?topic=cli-install-devtools-manually

Pls close this issue.
