### ISSUE TITLE
Broken link for:  [IBM Cloud Schematics command reference]

### ISSUE THREAD

**Issue by rodrigolara1** [ibm-cloud-docs/cli#5]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

broken link for:  [IBM Cloud Schematics command reference](https://cloud.ibm.com/docs/schematics?topic=schematics-setup-cli)
https://cloud.ibm.com/docs/cli?topic=cli-install-devtools-manually#idt-install-kubernetes-cli-plugin

2. Is this issue in reference to a specific page? If so, please provide a link.
![image](https://user-images.githubusercontent.com/131889203/234652770-c0ee12e9-9ff6-4d26-b527-ecf785aeb61c.png)
![image](https://user-images.githubusercontent.com/131889203/234652801-24b2813e-1c1b-4694-b0ff-860cb3185685.png)

3. Do you have a suggestion about how to resolve the issue?

**Comment by christoc-ibm** [comment]
@michaelbowler - For your action. I already added it to the CLI epic with a manual link, so you shouldn't need to create a separate doc issue for this.

**Comment by michaelbowler** [comment]
@christoc-ibm - this link has already been reported and fixed in https://github.com/ibm-cloud-docs/cli/issues/4
