### ISSUE TITLE
'ibmcloud enterprise account-delete' missing from CLI documentation

### ISSUE THREAD

**Issue by john-d-burke** [ibm-cloud-docs/cli#6]
The CLI 2.16 version shows the command:

>ibmcloud version
ibmcloud version 2.16.0+492aff3-2023-04-06T16:13:44+00:00

C:\Users\JohnBurke>ibmcloud enterprise help account-delete
NAME:
  account-delete - Delete an account

USAGE:
  ibmcloud enterprise account-delete (-n, --name NAME | --id ID) [-q, --quiet]

OPTIONS:
  --id value              ID of the account group
  -n value, --name value  Name of the account group
  -q, --quiet             Suppress verbose output

But the CLI documentation doesn't show the command:

https://cloud.ibm.com/docs/cli?topic=cli-ibmcloud_enterprise

**Comment by christoc-ibm** [comment]
@john-d-burke - Thanks for pointing this out. I added this item to our backlog, and it will be prioritized. Thanks again!
