### ISSUE TITLE
Can we update the doc for installation details on M1 Macs.

### ISSUE THREAD

**Issue by souvmaju-us** [ibm-cloud-docs/cli#6]
Can the Installation details be updated in the doc based on the following release, that brought in AS-IS support for IBMCloud CLI for Apple silicon:-
https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases/tag/v2.6.0

**Comment by christoc-ibm** [comment]
@souvmaju-us - Is this the doc link that you're looking at?

https://cloud.ibm.com/docs/cli?topic=cli-install-ibmcloud-cli#shell_install

I'm in contact with dev on this and will update this issue when I have more info.

**Comment by christoc-ibm** [comment]
The answer from dev is:

The shell install for Mac does not support M1, but I do see the Linux install does support ARM for Linux (which is AS-IS).
