### ISSUE TITLE
Wrong installation command for Windows™ 10 Pro.

### ISSUE THREAD

**Issue by r3sun** [ibm-cloud-docs/cli#8]
Hello!

The installation command for Windows™ 10 Pro provided in these links both are is wrong:

[cli-getting-started](https://github.com/ibm-cloud-docs/cli/blob/master/index.md)

[GitHub .md file](https://cloud.ibm.com/docs/cli?topic=cli-getting-started)

The command is:

```
iex(New-Object Net.WebClient).DownloadString('https://clis.cloud.ibm.com/install/powershell')
```

PowerShell produces this error while running this command:

```
PS C:\Users\_resun> iex(New-Object Net.WebClient).DownloadString('https://clis.cloud.ibm.com/install/powershell')iex(New-Object Net.WebClient).DownloadString('https://clis.cloud.ibm.com/install/powershell')
Invoke-Expression : A positional parameter cannot be found that accepts argument 'iex'.
At line:1 char:1
+ iex(New-Object Net.WebClient).DownloadString('https://clis.cloud.ibm. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-Expression], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```

There would be a space after __iex__. please fix this as fast as possible.

Thank you.

_resun.

**Comment by christoc-ibm** [comment]
Thank you for reporting this. 

We verified that it works with or without a space on our test system. Since it might not work on all systems (such as yours) without a space, we've added a space in the docs.

The updates will be visible sometime today. Thanks again.

**Comment by r3sun** [comment]
You are welcome.
